### ISSUE TITLE
Unable to Run, Asking for Password while installing pods.

### ISSUE THREAD

**Issue by faisalriazgoraya** [pia-foss/vpn-ios#15]
# Summary

### Steps to reproduce
Clone the code and then run command pod install. See the result.
Remove passcode restrition.

**Comment by ueshiba** [comment]
Hello @faisalriazgoraya 

You need to comment and uncomment the following pod libraries:

```
    pod "PIAAccountModule", :git => "#{$git_root}/#{$accounts_repo}"
    #pod "PIAAccountModule", :git => "#{$gitlab_kn_root}/#{$accounts_gitlab_repo}", :commit => '6116a38'
    pod "PIARegions", :git => "#{$git_root}/#{$regions_repo}"
    #pod "PIARegions", :git => "#{$gitlab_kn_root}/#{$regions_gitlab_repo}", :commit => '3b9395f'

```

Regards,
Jose

**Comment by zubairahmad2** [comment]
> Hello @faisalriazgoraya
> 
> You need to comment and uncomment the following pod libraries:
> 
> ```
>     pod "PIAAccountModule", :git => "#{$git_root}/#{$accounts_repo}"
>     #pod "PIAAccountModule", :git => "#{$gitlab_kn_root}/#{$accounts_gitlab_repo}", :commit => '6116a38'
>     pod "PIARegions", :git => "#{$git_root}/#{$regions_repo}"
>     #pod "PIARegions", :git => "#{$gitlab_kn_root}/#{$regions_gitlab_repo}", :commit => '3b9395f'
> ```
> 
> Regards,
> Jose

hi I also want to work but after comment and uncomment of these links same issue is happening please help more
these are my commands below: 
Zubair-Ahmed-MacBook-Pro:vpn-ios ch.usman$ pod install
Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
Analyzing dependencies
[!] The version of CocoaPods used to generate the lockfile (1.10.1) is higher than the version of the current executable (1.10.0). Incompatibility issues may arise.
Pre-downloading: `PIAAccountModule` from `https://github.com/pia-foss/mobile-common-account`
Pre-downloading: `PIACSIModule` from `git@codex.londontrustmedia.com:mobile/csi.git`, commit `8185dc9215cf942dc4691efb9ae1d62066f3a9e2`
git@codex.londontrustmedia.com's password:

**Comment by ueshiba** [comment]
@zubairahmad2 you need to do the same for the `PIACSIModule` module

**Comment by zubairahmad2** [comment]
> @zubairahmad2 you need to do the same for the `PIACSIModule` module

ok you mean to say that I comment and uncomment same module right ?

**Comment by zubairahmad2** [comment]
> @zubairahmad2 you need to do the same for the `PIACSIModule` module

I have Benn done same but same issue 
Zubair-Ahmed-MacBook-Pro:vpn-ios ch.usman$ pod install
Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
Analyzing dependencies
Pre-downloading: `PIAAccountModule` from `https://github.com/pia-foss/mobile-common-account`
Pre-downloading: `PIACSIModule` from `https://github.com/pia-foss/mobile-common-csi`
Pre-downloading: `PIALibrary` from `git@codex.londontrustmedia.com:ios/client-library-apple.git`, commit `fe1b5e4`
git@codex.londontrustmedia.com's password:
