### ISSUE TITLE
Error installing PIAKPIModule

### ISSUE THREAD

**Issue by AMJ-7** [pia-foss/vpn-ios#22]
pod install error :

```
[!] Error installing PIAKPIModule
[!] Failed to download 'PIAKPIModule': [!] /usr/bin/git clone git@gitlab.kape.com:pia-mobile/shared/kpi.git /var/folders/pf/jwjt8jq5349dd24d6f0mb_sc0000gp/T/d20221113-10943-6526ya --template=

Cloning into '/var/folders/pf/jwjt8jq5349dd24d6f0mb_sc0000gp/T/d20221113-10943-6526ya'...
ssh: connect to host gitlab.kape.com port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


```

how can I solve this ?

**Comment by xv-laura-s** [comment]
Hi @AMJ-7 . Sorry for the very late response. This issue has been fixed in our latest version. I recommend you clone again this repo and try to build.
We have moved away from `Cocoapods` and we are managing dependencies with `SPM`.  
All the dependencies, including `PIAKPI` have also been moved to public repos.
